"""empty message

Revision ID: 466133e5f670
Revises: db5d1b3f3a0b
Create Date: 2024-06-15 00:20:10.244645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466133e5f670'
down_revision = 'db5d1b3f3a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
